// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mingielewicz_inzynierka.Data;

#nullable disable

namespace mingielewiczinzynierka.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230119000001_fix unique")]
    partial class fixunique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idText")
                        .HasColumnType("integer");

                    b.Property<int>("idTranslation")
                        .HasColumnType("integer");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("idText");

                    b.HasIndex("idTranslation");

                    b.HasIndex("idUser", "idTranslation")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Text", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.Property<string>("language")
                        .HasColumnType("text");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Translation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idText")
                        .HasColumnType("integer");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.Property<string>("language")
                        .HasColumnType("text");

                    b.Property<int>("sectionId")
                        .HasColumnType("integer");

                    b.Property<string>("translatedText")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idText");

                    b.HasIndex("idUser");

                    b.HasIndex("sectionId", "idText", "language")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("isAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "Redziok@wp.pl",
                            isAdmin = true,
                            login = "Redziok",
                            password = "$2a$11$49Lbe.6QAiCZK4ZtmgcpYOyZeSnpDkc834WO0bNMrb90CzpfnuJUa"
                        });
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Rating", b =>
                {
                    b.HasOne("mingielewicz_inzynierka.Models.Text", "text")
                        .WithMany()
                        .HasForeignKey("idText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mingielewicz_inzynierka.Models.Translation", "translation")
                        .WithMany()
                        .HasForeignKey("idTranslation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mingielewicz_inzynierka.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("text");

                    b.Navigation("translation");

                    b.Navigation("user");
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Text", b =>
                {
                    b.HasOne("mingielewicz_inzynierka.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("mingielewicz_inzynierka.Models.Translation", b =>
                {
                    b.HasOne("mingielewicz_inzynierka.Models.Text", "text")
                        .WithMany()
                        .HasForeignKey("idText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mingielewicz_inzynierka.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("text");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
